pipeline {
    agent any

    tools {
        // Install the Maven version configured as "M3" and add it to the path.
        maven "M3"
        
    }

    stages {
        stage('Build') {
            steps {
                sh 'mvn -f Calculator/pom.xml -B -DskipTests clean package'
            }
        }
        stage('Sonar Scan') {
            steps {
                withSonarQubeEnv('Sonar Server') {
                    sh 'mvn -f Calculator/pom.xml org.sonarsource.scanner.maven:sonar-maven-plugin:3.7.0.1746:sonar'
                }
            }
        }
         stage('Test') {
            steps {
                sh 'mvn -f Calculator/pom.xml test'
            }
            post {
                // If Maven was able to run the tests, even if some of the test
                // failed, record the test results and archive the jar file.
                success {
                    junit '**/target/surefire-reports/TEST-*.xml'
                    // archiveArtifacts 'target/*.jar'
                }
            }
            post {
                always {
                    junit '**/target/surefire-reports/*.xml'
                }
            }
        }
    }
}
